"""Train XGBoost from video-window dataset.

Expects dataset generated by pipeline/video_dataset_builder.py:
    data/video/windows_master.csv

Run:
    python models/train_xgboost_video.py
"""

from __future__ import annotations

from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler


ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "video" / "windows_master.csv"
OUT = ROOT / "models"
OUT.mkdir(parents=True, exist_ok=True)

FEATURE_COLS = [
    "vehicle_count",
    "proximity_score",
    "pedestrian_flag",
    "mean_flow",
    "flow_variance",
    "braking_flag",
    "lane_change_flag",
    "road_type_id",
    "weather_id",
]
TARGET_COL = "eco_score_proxy"


def load_data():
    if not DATA_PATH.exists():
        raise FileNotFoundError(
            f"Missing dataset at {DATA_PATH}. Run pipeline/video_dataset_builder.py first."
        )

    df = pd.read_csv(DATA_PATH)
    if df.empty:
        raise ValueError("windows_master.csv is empty. Build dataset with valid videos first.")

    missing = [c for c in FEATURE_COLS + [TARGET_COL, "split"] if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset missing required columns: {missing}")

    tr = df[df["split"] == "train"].copy()
    va = df[df["split"] == "val"].copy()
    te = df[df["split"] == "test"].copy()

    if tr.empty or va.empty or te.empty:
        raise ValueError("train/val/test splits are incomplete in dataset")

    X_train = tr[FEATURE_COLS]
    X_val = va[FEATURE_COLS]
    X_test = te[FEATURE_COLS]
    y_train = tr[TARGET_COL].astype(float)
    y_val = va[TARGET_COL].astype(float)
    y_test = te[TARGET_COL].astype(float)

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_val_s = scaler.transform(X_val)
    X_test_s = scaler.transform(X_test)

    X_train_s = pd.DataFrame(X_train_s, columns=FEATURE_COLS)
    X_val_s = pd.DataFrame(X_val_s, columns=FEATURE_COLS)
    X_test_s = pd.DataFrame(X_test_s, columns=FEATURE_COLS)

    return X_train_s, X_val_s, X_test_s, y_train, y_val, y_test, scaler


def evaluate(name, model, X, y):
    p = model.predict(X)
    rmse = np.sqrt(mean_squared_error(y, p))
    mae = mean_absolute_error(y, p)
    r2 = r2_score(y, p)
    print(f"[xgb_video] {name:10s} RMSE={rmse:.4f} MAE={mae:.4f} R2={r2:.4f}")
    return rmse, mae, r2


def main():
    try:
        from xgboost import XGBRegressor
    except Exception as e:
        raise RuntimeError(
            "XGBoost import failed. On macOS this is usually missing OpenMP runtime. "
            "Install with: brew install libomp"
        ) from e

    print("[xgb_video] Loading dataset ...")
    X_train, X_val, X_test, y_train, y_val, y_test, scaler = load_data()

    model = XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        eval_metric="rmse",
        random_state=42,
        n_jobs=-1,
        early_stopping_rounds=30,
    )

    print("[xgb_video] Training ...")
    model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        verbose=50,
    )

    print("\n[xgb_video] Evaluation")
    evaluate("Train", model, X_train, y_train)
    evaluate("Val", model, X_val, y_val)
    evaluate("Test", model, X_test, y_test)

    model_path = OUT / "xgb_scorer.pkl"
    joblib.dump(model, model_path)
    print(f"[xgb_video] Saved model -> {model_path}")

    scaler_path = OUT / "scaler.pkl"
    joblib.dump(
        {
            "scaler": scaler,
            "feature_cols": FEATURE_COLS,
            "schema": "xgb_v3_video_windows_9cols",
            "target_col": TARGET_COL,
            "data_source": str(DATA_PATH),
        },
        scaler_path,
    )
    print(f"[xgb_video] Saved scaler -> {scaler_path}")

    try:
        import shap
        explainer = shap.TreeExplainer(model)
        x_shap = X_test.iloc[:500]
        shap_values = explainer.shap_values(x_shap)
        plt.figure(figsize=(10, 6))
        shap.summary_plot(shap_values, x_shap, show=False)
        shap_path = OUT / "shap_summary_video.png"
        plt.savefig(shap_path, bbox_inches="tight", dpi=150)
        plt.close()
        print(f"[xgb_video] Saved SHAP -> {shap_path}")
    except Exception as e:
        print(f"[xgb_video] SHAP skipped: {e}")

    print("[xgb_video] Done.")


if __name__ == "__main__":
    main()
